config:
  argenpills-crud-infrastructure:api: api.argenpills.info
  argenpills-crud-infrastructure:images: images.argenpills.info
  argenpills-crud-infrastructure:zone: argenpills.info
  aws:profile: ap_prod
  aws:region: us-east-1
