name: Run Tests

on:
  push:
    branches: [ ]
  pull_request:
    branches: [ ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to use'     
        required: true
        default: 'main'    

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: oven-sh/setup-bun@v2
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies for apps
      run: |
        bun install
        cd argenpills-auth
        bun install
        cd ..
        cd argenpills-crud
        bun install
    - name: Install dependencies and run tests
      run: |
        cd tests
        bun install
        bun jest
