name: Node.js Tests

on:
  push:
    branches:
      - tests  # Temporary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # You can specify the Node.js version you need
    - name: Change directory
      run: cd argenpills-crud/tests
      
    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test -t index
